# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ARVIND\GIT\TaxCalculator\AddData.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddWindow(object):
    def setupUi(self, AddWindow):
        AddWindow.setObjectName("AddWindow")
        AddWindow.resize(445, 419)
        self.centralwidget = QtWidgets.QWidget(AddWindow)
        self.centralwidget.setObjectName("centralwidget")
        #self.centralwidget.setStyleSheet("QPushButton::hover""{""color:black;""}""QPushButton::clicked""{""color:Green;""}")
        self.WINDOW = QtWidgets.QFrame(self.centralwidget)
        self.WINDOW.setGeometry(QtCore.QRect(20, 20, 401, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WINDOW.sizePolicy().hasHeightForWidth())
        self.WINDOW.setSizePolicy(sizePolicy)
        self.WINDOW.setStyleSheet("background-color:rgb(250,250,250);")
        self.WINDOW.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WINDOW.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WINDOW.setObjectName("WINDOW")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.WINDOW)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TITLE = QtWidgets.QFrame(self.WINDOW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TITLE.sizePolicy().hasHeightForWidth())
        self.TITLE.setSizePolicy(sizePolicy)
        self.TITLE.setMinimumSize(QtCore.QSize(0, 30))
        self.TITLE.setStyleSheet("border-color:rgb(102, 204, 255);\n"
"border:4px;")
        self.TITLE.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TITLE.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TITLE.setObjectName("TITLE")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.TITLE)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.TITLE)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(98, 102, 244);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.close = QtWidgets.QPushButton(self.TITLE)
        self.close.setStyleSheet("background-color:transparent;")
        self.close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/feather/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon)
        self.close.setObjectName("close")
        self.horizontalLayout.addWidget(self.close)
        self.verticalLayout.addWidget(self.TITLE)
        self.MIDDLE = QtWidgets.QFrame(self.WINDOW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MIDDLE.sizePolicy().hasHeightForWidth())
        self.MIDDLE.setSizePolicy(sizePolicy)
        self.MIDDLE.setStyleSheet("QFrame { border: 2px solid blue }.")
        self.MIDDLE.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MIDDLE.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MIDDLE.setObjectName("MIDDLE")
        self.gridLayout = QtWidgets.QGridLayout(self.MIDDLE)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.MIDDLE)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(98, 102, 244);\n"
"border: 0px solid black;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.FilePath = QtWidgets.QPushButton(self.MIDDLE)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.FilePath.setFont(font)
        self.FilePath.setStyleSheet("""QPushButton {
            background-color: rgb(102, 204, 255); 
            color:rgb(250,250,250);
            border:2px light black;
        }
        QPushButton:hover {
            color: light-Green;
        }
    """)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/feather/file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FilePath.setIcon(icon1)
        self.FilePath.setObjectName("FilePath")
        self.gridLayout.addWidget(self.FilePath, 0, 1, 1, 1)
        self.Month = QtWidgets.QDateEdit(self.MIDDLE,calendarPopup=True)
        self.Month.setStyleSheet("border-width: 5px;\n"
"color: rgb(26, 26, 26);\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(250,250,250);")
        self.Month.setDisplayFormat("MM-yyyy")
        self.Month.setObjectName("Month")
        self.gridLayout.addWidget(self.Month, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.MIDDLE)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(98, 102, 244);\n"
"border: 0px solid black;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.MIDDLE)
        self.LAST = QtWidgets.QFrame(self.WINDOW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LAST.sizePolicy().hasHeightForWidth())
        self.LAST.setSizePolicy(sizePolicy)
        self.LAST.setMinimumSize(QtCore.QSize(0, 40))
        self.LAST.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LAST.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LAST.setObjectName("LAST")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.LAST)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Status = QtWidgets.QLabel(self.LAST)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Status.sizePolicy().hasHeightForWidth())
        self.Status.setSizePolicy(sizePolicy)
        self.Status.setObjectName("Status")
        self.horizontalLayout_2.addWidget(self.Status)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.OK = QtWidgets.QPushButton(self.LAST)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OK.sizePolicy().hasHeightForWidth())
        self.OK.setSizePolicy(sizePolicy)
        self.OK.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.OK.setFont(font)
        self.OK.setStyleSheet("""QPushButton {
            background-color: rgb(102, 204, 255); 
            color:rgb(250,250,250);
            border:2px light black;
        }
        QPushButton:hover {
            color: light-Green;
        }
    """)
        self.OK.setObjectName("OK")
        self.horizontalLayout_2.addWidget(self.OK)
        self.verticalLayout.addWidget(self.LAST)
        AddWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 445, 22))
        self.menubar.setObjectName("menubar")
        AddWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddWindow)
        self.statusbar.setObjectName("statusbar")
        AddWindow.setStatusBar(self.statusbar)
        AddWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)


        self.retranslateUi(AddWindow)
        QtCore.QMetaObject.connectSlotsByName(AddWindow)

    def retranslateUi(self, AddWindow):
        _translate = QtCore.QCoreApplication.translate
        AddWindow.setWindowTitle(_translate("AddWindow", "MainWindow"))
        self.label.setText(_translate("AddWindow", "ADD TDS DATA"))
        self.label_2.setText(_translate("AddWindow", "            ADD FILE PATH"))
        self.FilePath.setText(_translate("AddWindow", "   FILE PATH"))
        self.label_3.setText(_translate("AddWindow", "            MONTH/YEAR"))
        self.Status.setText(_translate("AddWindow", "Status: No File Added"))
        self.OK.setText(_translate("AddWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddWindow = QtWidgets.QMainWindow()
    ui = Ui_AddWindow()
    ui.setupUi(AddWindow)
    AddWindow.show()
    sys.exit(app.exec_())
