# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\common\TaxCalculator\Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
import pandas as pd
from tkinter import filedialog,messagebox
from win32com.client import Dispatch
from os.path import exists
import sqlite3
from datetime import date
from PyQt5 import QtCore, QtGui, QtWidgets
from AddData import *

class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1213, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"border: none;\n"
"background-color:transparent;\n"
"background:none;\n"
"padding:0;\n"
"margin:0;\n"
"color:#fff;\n"
"}\n"
"#centralwidget{\n"
"background-color:#FFFF;\n"
"}\n"
"#LeftMenu{\n"
"background-color:rgb(98, 102, 244);\n"
"}\n"
"QTabBar::tab {height: 40px; width: 100px;}"                                         
"QpushButton{\n"
"text-align:left;\n"
"padding: 2px 5px;\n"
"}"
"QPushButton::hover"
                             "{"
                             "background-color : rgb(210, 210, 210);"
                             "}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftMenu = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LeftMenu.sizePolicy().hasHeightForWidth())
        self.LeftMenu.setSizePolicy(sizePolicy)
        self.LeftMenu.setObjectName("LeftMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LeftMenu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.LeftMenu)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.MenuButton = QtWidgets.QPushButton(self.frame)
        self.MenuButton.setAutoFillBackground(False)
        self.MenuButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/20x20/cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MenuButton.setIcon(icon)
        self.MenuButton.setIconSize(QtCore.QSize(32, 32))
        self.MenuButton.setObjectName("MenuButton")
        self.verticalLayout_5.addWidget(self.MenuButton)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 15, 0, 15)
        self.verticalLayout_4.setSpacing(40)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Home = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        self.Home.setFont(font)
        self.Home.setStyleSheet("back-ground=rgb(255, 255, 255)")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/20x20/cil-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Home.setIcon(icon1)
        self.Home.setIconSize(QtCore.QSize(20, 20))
        self.Home.setObjectName("Home")
        self.verticalLayout_4.addWidget(self.Home)
        self.LIST = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.LIST.setFont(font)
        self.LIST.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LIST.setText("  LIST")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/20x20/cil-library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LIST.setIcon(icon2)
        self.LIST.setIconSize(QtCore.QSize(20, 20))
        self.LIST.setObjectName("LIST")
        self.verticalLayout_4.addWidget(self.LIST)
    
        self.FILTER = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.FILTER.setFont(font)
        self.FILTER.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FILTER.setText(" FILTER")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/20x20/cil-transfer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FILTER.setIcon(icon2)
        self.FILTER.setIconSize(QtCore.QSize(20, 20))
        self.FILTER.setObjectName("FILTER")
        self.verticalLayout_4.addWidget(self.FILTER)
    
        self.ADD = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.ADD.setFont(font)
        self.ADD.setText("  ADD")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/20x20/cil-medical-cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ADD.setIcon(icon3)
        self.ADD.setIconSize(QtCore.QSize(20, 23))
        self.ADD.setObjectName("ADD")
        self.verticalLayout_4.addWidget(self.ADD)

        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_3.setSpacing(25)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SETTINGS = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.SETTINGS.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/20x20/cil-settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SETTINGS.setIcon(icon4)
        self.SETTINGS.setIconSize(QtCore.QSize(20, 20))
        self.SETTINGS.setObjectName("SETTINGS")
        self.verticalLayout_3.addWidget(self.SETTINGS)
        self.HELP = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.HELP.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/20x20/cil-lightbulb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HELP.setIcon(icon5)
        self.HELP.setIconSize(QtCore.QSize(20, 20))
        self.HELP.setObjectName("HELP")
        self.verticalLayout_3.addWidget(self.HELP)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.LeftMenu)
        self.Main = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main.sizePolicy().hasHeightForWidth())
        self.Main.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.Main.setFont(font)
        self.Main.setStyleSheet("")
        self.Main.setObjectName("Main")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Main)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.TITLEBAR = QtWidgets.QFrame(self.Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TITLEBAR.sizePolicy().hasHeightForWidth())
        self.TITLEBAR.setSizePolicy(sizePolicy)
        self.TITLEBAR.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TITLEBAR.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TITLEBAR.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TITLEBAR.setObjectName("TITLEBAR")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.TITLEBAR)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TITLE = QtWidgets.QLabel(self.TITLEBAR)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.TITLE.setFont(font)
        self.TITLE.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(85, 0, 255);")
        self.TITLE.setWordWrap(False)
        self.TITLE.setObjectName("TITLE")
        self.horizontalLayout_2.addWidget(self.TITLE)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.CloseButton = QtWidgets.QPushButton(self.TITLEBAR)
        self.CloseButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/feather/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CloseButton.setIcon(icon6)
        self.CloseButton.setIconSize(QtCore.QSize(20, 20))
        self.CloseButton.setObjectName("CloseButton")
        self.horizontalLayout_2.addWidget(self.CloseButton)
        self.MaximizeButtton = QtWidgets.QPushButton(self.TITLEBAR)
        self.MaximizeButtton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/feather/maximize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MaximizeButtton.setIcon(icon7)
        self.MaximizeButtton.setIconSize(QtCore.QSize(20, 20))
        self.MaximizeButtton.setObjectName("MaximizeButtton")
        self.horizontalLayout_2.addWidget(self.MaximizeButtton)
        self.MinimizeButton = QtWidgets.QPushButton(self.TITLEBAR)
        self.MinimizeButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.MinimizeButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/feather/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MinimizeButton.setIcon(icon8)
        self.MinimizeButton.setIconSize(QtCore.QSize(20, 20))
        self.MinimizeButton.setObjectName("MinimizeButton")
        self.horizontalLayout_2.addWidget(self.MinimizeButton)
        self.CloseButton.raise_()
        self.MinimizeButton.raise_()
        self.MaximizeButtton.raise_()
        self.TITLE.raise_()
        self.verticalLayout_6.addWidget(self.TITLEBAR)
        self.Window = QtWidgets.QFrame(self.Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Window.sizePolicy().hasHeightForWidth())
        self.Window.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        self.Window.setFont(font)
        self.Window.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.Window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Window.setObjectName("Window")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Window)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.FILTERWINDOW = QtWidgets.QFrame(self.Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FILTERWINDOW.sizePolicy().hasHeightForWidth())
        self.FILTERWINDOW.setSizePolicy(sizePolicy)
        self.FILTERWINDOW.setMinimumSize(QtCore.QSize(0, 0))
        self.FILTERWINDOW.setStyleSheet("background-color:rgb(98, 102, 244);")
        self.FILTERWINDOW.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FILTERWINDOW.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FILTERWINDOW.setObjectName("FILTERWINDOW")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.FILTERWINDOW)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.From = QtWidgets.QLabel(self.FILTERWINDOW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.From.sizePolicy().hasHeightForWidth())
        self.From.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.From.setFont(font)
        self.From.setObjectName("From")
        self.horizontalLayout_3.addWidget(self.From)
        self.FromDate = QtWidgets.QDateTimeEdit(self.FILTERWINDOW,calendarPopup=True)
        font = QtGui.QFont("Segoe")
        font.setPointSize(11)
        font.setBold(True)
        self.FromDate.setFont(font)
        self.FromDate.setStyleSheet("border-width: 5px;\n"
"color: rgb(26, 26, 26);\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(250,250,250);")
        self.FromDate.setDisplayFormat("MM-yyyy")
        self.FromDate.setObjectName("FromDate")
        self.horizontalLayout_3.addWidget(self.FromDate)
        self.To = QtWidgets.QLabel(self.FILTERWINDOW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.To.sizePolicy().hasHeightForWidth())
        self.To.setSizePolicy(sizePolicy)
        font = QtGui.QFont("Segoe")
        font.setPointSize(11)
        font.setBold(True)
        self.To.setFont(font)
        self.To.setObjectName("To")
        self.horizontalLayout_3.addWidget(self.To)
        self.ToDate = QtWidgets.QDateTimeEdit(self.FILTERWINDOW,calendarPopup=True)
        self.ToDate.setDisplayFormat("MM-yyyy")
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.ToDate.setFont(font)
        self.ToDate.setStyleSheet("border-width: 15px;\n"
"color: rgb(26, 26, 26);\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(250,250,250);")
        self.ToDate.setObjectName("ToDate")
        self.horizontalLayout_3.addWidget(self.ToDate)
        self.FANumber = QtWidgets.QLabel(self.FILTERWINDOW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FANumber.sizePolicy().hasHeightForWidth())
        self.FANumber.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.FANumber.setFont(font)
        self.FANumber.setObjectName("FANumber")
        self.horizontalLayout_3.addWidget(self.FANumber)
        self.FaText = QtWidgets.QPlainTextEdit(self.FILTERWINDOW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FaText.sizePolicy().hasHeightForWidth())
        self.FaText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.FaText.setFont(font)
        self.FaText.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:rgb(0,0,0);\n"
"font: 9pt \"Segoe UI\";")
        self.FaText.setObjectName("FaText")
        self.horizontalLayout_3.addWidget(self.FaText)
        self.FilterButton = QtWidgets.QPushButton(self.FILTERWINDOW)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.FilterButton.setFont(font)
        self.FilterButton.setStyleSheet("background-color: rgb(102, 204, 255);padding: 6px;")
        icon = QtGui.QIcon.fromTheme("accessories-calculator")
        self.FilterButton.setIcon(icon)
        self.FilterButton.setObjectName("FilterButton")
        self.horizontalLayout_3.addWidget(self.FilterButton)
        self.FromDate.raise_()
        self.From.raise_()
        self.ToDate.raise_()
        self.To.raise_()
        self.FANumber.raise_()
        self.FilterButton.raise_()
        self.FaText.raise_()
        self.verticalLayout_7.addWidget(self.FILTERWINDOW)
        self.tabWidget = QtWidgets.QTabWidget(self.Window)
        self.tabWidget.setStyleSheet("background-color:rgb(250, 250, 250);color:rgb(0, 0, 0);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        #self.tabwidget.setStyleSheet("QTabBar::tab { height: 40px; width: 100px;}")
        self.tabWidget.addTab(DFEditor(),"DB")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        #self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_7.addWidget(self.tabWidget)
        self.verticalLayout_6.addWidget(self.Window)
        self.horizontalLayout.addWidget(self.Main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1213, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MenuButton.setToolTip(_translate("MainWindow", "Menu"))
        self.Home.setToolTip(_translate("MainWindow", "HOME"))
        self.Home.setText(_translate("MainWindow", " HOME"))
        self.LIST.setToolTip(_translate("MainWindow", "LIST"))
        self.ADD.setToolTip(_translate("MainWindow", "LIST"))
        self.ADD.setText(_translate("MainWindow", " ADD"))
        self.SETTINGS.setToolTip(_translate("MainWindow", "SETTINGS"))
        self.SETTINGS.setText(_translate("MainWindow", " SETTINGS"))
        self.HELP.setToolTip(_translate("MainWindow", "HELP"))
        self.HELP.setText(_translate("MainWindow", "  HELP"))
        self.TITLE.setText(_translate("MainWindow", "TAX CALCULATOR"))
        self.From.setText(_translate("MainWindow", "       FROM"))
        self.To.setText(_translate("MainWindow", "             TO"))
        self.FANumber.setText(_translate("MainWindow", "     FA Number:"))
        self.FaText.setPlainText(_translate("MainWindow", ""
""))
        self.FilterButton.setText(_translate("MainWindow", "FILTER"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
#import resource_rc
class DFEditor(QtWidgets.QWidget):
    global df2
    conn = sqlite3.connect('master.db')
    c = conn.cursor()
    listOfTables = c.execute(
  """SELECT name FROM sqlite_master WHERE type='table'
  AND name='TaxDB'; """).fetchall()
    if len(listOfTables) == 0:
        def __init__(self):
            super().__init__()
            self.resize(1200, 800)
            mainLayout = QtWidgets.QVBoxLayout()
            self.label = QtWidgets.QLabel()
            self.label.setObjectName("label")
            self.label.setStyleSheet("border-width: 5px;\n"
            "color: rgb(26, 26, 26);\n"
            "background-color: rgb(255, 255, 255);\n"
            "border-color: rgb(250,250,250);"
            "font: 15pt \"Segoe UI\";")
            self.label.setText(f'Customer Yet To Reach Transaction Amount of 5000000')
            mainLayout.addWidget(self.label)
            self.setLayout(mainLayout)
    else:
        MasterDf = pd.read_sql("select * from DB", con=conn)
        MasterDf = MasterDf[MasterDf['Transaction Amount (Rs.)'] >= 5000000]
        print(MasterDf)
        df2 = MasterDf
        def __init__(self):
            super().__init__()
            self.resize(1200, 800)

            mainLayout = QtWidgets.QVBoxLayout()
            stylesheet = ""
            '''
            stylesheet = """
            QHeaderView::section{background-color: rgb(51, 204, 204)}
            """       
            '''
            self.table = TableWidget3(DFEditor.MasterDf)
            self.table.setStyleSheet(u"QTableWidget {	\n"
"	background-color: rgb(250, 250, 250);\n"
"	padding: 10px;\n"
"	border-radius: 5px;\n"
"	gridline-color: rgb(0, 0, 0);\n"
"	border-bottom: 1px solid rgb(102, 204, 255);\n"
"   font: 9pt \"Segoe UI\";"
"}\n"
"QTableWidget::item{\n"
"	border-color: rgb(102, 204, 255);\n"
"	padding-left: 5px;\n"
"	padding-right: 5px;\n"
"	gridline-color: rgb(102, 204, 255);\n"
"}\n"
"QTableWidget::item:selected{\n"
"	background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"	border-radius: 0px;\n"
"}\n"
" QScrollBar:vertical {\n"
"	border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"	border-radius: 0px;\n"
" }\n"
"QHeaderView::section{\n"
"	Background-color: rgb(102, 204, 255);\n"
"	max-width: 30px;\n"
"	border: 1px solid rgb(32, 34, 42);\n"
"   border-bottom: 1px solid rgb(102, 204, 255);\n"
"   border-right: 1px solid rgb(102, 204, 255);\n"
"}\n"
""
                        "QTableWidget::horizontalHeader {	\n"
"	background-color: rgb(81, 255, 0);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(32, 34, 42);\n"
"	background-color: rgb(102, 204, 255);\n"
"	padding: 3px;\n"
"	border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(102, 204, 255);\n"
"    border: 1px solid rgb(32, 34, 42);\n"
"	background-color: rgb(102, 204, 255);\n"
"	padding: 3px;\n"
"	border-top-left-radius: 0px;\n"
"   border-top-right-radius: 0px;\n"
"}\n"
"")
            mainLayout.addWidget(self.table)
            self.setLayout(mainLayout)
            
        def print_DF_Values(self):
            print(self.table.df)
            df2 = self.table.df
class AppDemo():
    def __init__(self):
            super().__init__()
            self.resize(1200, 800)
            print("AppDemo")
            mainLayout = QtWidgets.QVBoxLayout()
            stylesheet = """
            QHeaderView::section{background-color: rgb(98, 102, 244);}
            """       
            self.table = TableWidget3(DFEditor.MasterDf)
            self.table.setStyleSheet(stylesheet)
            mainLayout.addWidget(self.table)
            self.setLayout(mainLayout)

class FloatDelegate(QtWidgets.QItemDelegate):
    def __init__(self, parent=None):
        super().__init__()

    def createEditor(self, parent, option, index):
        editor = QLineEdit(parent)
        editor.setValidator(QDoubleValidator())
        return editor
class TableWidget3(QtWidgets.QTableWidget):
    def __init__(self, df):
        super().__init__()
        self.df = df
        self.setStyleSheet('background-color: rgb(98, 102, 244);font-size: 20px;')
        nRows, nColumns = self.df.shape
        self.setColumnCount(nColumns)
        self.setRowCount(nRows)
        QtWidgets.QHeaderView
        self.setHorizontalHeaderLabels(('Account Name', 'Transaction Amount (Rs.)'))
        self.verticalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.horizontalHeader().setFixedHeight(30)
        self.setItemDelegateForColumn(1, FloatDelegate())
        # data insertion/
        for i in range(self.rowCount()):
            for j in range(self.columnCount()):
                self.setItem(i, j,
                             QtWidgets.QTableWidgetItem(str(self.df.iloc[i, j])))

        self.cellChanged[int, int].connect(self.updateDF)   
    QtWidgets.QTableWidgetItem
    def updateDF(self, row, column):
        text = self.item(row, column).text()
        self.df.iloc[row, column] = text

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
